version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: >
      sh -c "python tp2RedisMandalorian/mandalorian/setup_redis.py && python tp2RedisMandalorian/manage.py runserver 0.0.0.0:8000"
